name: CI

on:
  pull_request:
  push:
    branches: ['main']
  workflow_dispatch:

env:
  CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup-environment:
    uses: sebpalluel/web3-monorepo/.github/workflows/setup-environment.yml@main
  main:
    needs: setup-environment
    name: Nx Cloud - Main Job
    uses: sebpalluel/ci/.github/workflows/nx-cloud-main.yml@latest
    secrets:
      ENV_FILE: ${{ secrets.ENV_FILE }}
    with:
      runs-on: ubuntu-22.04
      artifacts-path: |
        dist/cypress
      artifacts-name: cypress
      environment-variables: |
        CYPRESS_CACHE_FOLDER=~/.cache/Cypress
      cypress_cache_path: ~/.cache/Cypress
      environment: staging
      init-commands: |
        pnpm exec nx-cloud record -- pnpm docker:test & pnpm docker:services
        # pnpm exec nx-cloud record -- pnpm docker:hasura-test-logs
        # pnpm exec nx-cloud record -- pnpm docker:hasura-engine-logs
        NX_CLOUD_DISTRIBUTED_EXECUTION=false pnpm nx is-services-launched

      parallel-commands: |
        pnpm nx workspace-lint
        pnpm nx format:check --verbose
        ## test relying in prisma + hasura not working in parallel, docker services not available ?
        pnpm nx affected --target=test-prisma --ci --code-coverage
        pnpm nx affected --target=test-hasura --ci --code-coverage
        pnpm nx affected --target=e2e --no-watch
      parallel-commands-on-agents: |
        pnpm affected:lint --parallel=3 &
        pnpm affected:build --parallel=3 &
        pnpm nx affected --target=test --parallel=3 --ci --code-coverage &
  agents:
    needs: setup-environment
    name: Nx Cloud - Agents
    uses: sebpalluel/ci/.github/workflows/nx-cloud-agents.yml@latest
    secrets:
      ENV_FILE: ${{ secrets.ENV_FILE }}
    with:
      runs-on: ubuntu-22.04
      environment: staging
      number-of-agents: 3
      init-commands: |
        pnpm prisma generate
