name: Nx Graph

on:
  push:
    branches: ['main']
    paths:
      - nx.json
      - workspace.json
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-environment:
    uses: sebpalluel/web3-monorepo/.github/workflows/setup-environment.yml@main
  generate-static-site:
    environment:
      name: NX Graph Page
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: generate nx graph
        run: pnpm nx-graph-static
      - name: Setup Nx Graph Page
        uses: actions/configure-pages@v2.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './static/nx-graph'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
