name: Setup Environment

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get Node.js version
        id: node-version
        run: echo "::set-output name=version::$(node --version)"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 'latest'
          run_install: false

      - name: Get pnpm cache directory path
        if: steps.package_manager.outputs.name == 'pnpm'
        id: pnpm-cache-dir-path
        run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Use the node_modules cache if available [pnpm]
        id: cache-node-modules-pnpm
        if: steps.package_manager.outputs.name == 'pnpm'
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-${{ steps.versions.outputs.node_version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ steps.versions.outputs.node_version }}-

      # we use the exact restore key to avoid Cypress binary snowballing
      # https://glebbahmutov.com/blog/do-not-let-cypress-cache-snowball/
      # https://github.com/cypress-io/cypress-example-kitchensink/blob/0cf2a960fea4804271a9e5273d2ed8e246dd9e21/.github/workflows/parallel.yml#L1-L1
      - name: Cache Cypress binary
        uses: actions/cache@v3
        id: cache-cypress-binary
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-

      - name: Install dependencies
        run: pnpm install

      - name: Install Cypress binary if no cache hit
        if: steps.cache-cypress-binary.outputs.cache-hit != 'true'
        run: pnpm cypress install

      ### Use in case cypress not found in cache
      # run: pnpm install && pnpm install cypress

      # - name: Check for Cypress cache binary
      #   run: |
      #     pnpm cypress cache path
      #     pnpm cypress cache list
      #     pnpm cypress verify
      #     pnpm cypress info
